[package]
name = "image-optimizer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive", "cargo"] }
glob = "0.3.2"
image = "0.25.5"
ravif = "0.11.11"
rayon = "1.10.0"
webp = "0.3.0"
